sudo : required
services: 
  - docker
language: node_js
node_js:
  - 8

before_install: 
  - npm i -g npm@6.9.0
  - docker build -t altair98/docker-react -f Dockerfile.dev .

scripts :
  - docker run altair98/docker-react npm run test -- --coverage