sudo : required
services: 
  - docker
language: node_js
before_install: 
  - docker build -t altair98/docker-react -f Dockerfile.dev .

scripts :
  - docker run altair98/docker-react npm run test -- --coverage